name: Build NixOS
description: Builds NixOS system
inputs:
  hostname:
    required: true
    description: Hostname
runs:
  using: 'composite'
  steps:
    - name: "NixOS: build ${{inputs.hostname}}"
      shell: bash
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/key

        echo "[GitHub CI] Building ${{inputs.hostname}} on remote"
        ssh ci-builder@nix-binary-cache.phip1611.dev $SSHOPTS <<EOF
          cd "$REMOTE_CI_PWD" || exit 1
          echo "[Remote Builder] Building ${{inputs.hostname}}"
          echo "[Remote Builder] pwd = " '$PWD'
          nice -n 19 nixos-rebuild build --flake .#${{inputs.hostname}}
        EOF
