name: Build NixOS
description: Builds a NixOS system on the remote builder
inputs:
  hostname:
    required: true
    description: Hostname
runs:
  using: 'composite'
  steps:
    - name: "NixOS: build ${{inputs.hostname}}"
      shell: bash
      run: |
        echo "[GitHub CI] Building ${{inputs.hostname}} on remote ..."
        ssh ci-builder@nix-binary-cache.phip1611.dev $SSHOPTS <<EOF
          set -euo pipefail
          cd "$REMOTE_CI_PWD" || exit 1
          echo "[Remote Builder] Building ${{inputs.hostname}}"
          echo "[Remote Builder] pwd = $REMOTE_CI_PWD"
          nice -n 19 nixos-rebuild build --flake .#${{inputs.hostname}} -L
        EOF
