name: Update Nix Flake
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours / 4 times a day
  workflow_dispatch: # Allow manual dispatch for testing
jobs:
  flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
      - name: Create GitHub App token
        if: env.skip != 'true'
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: '${{ secrets.FLAKE_AUTOUPDATE_APP_ID }}'
          private-key: '${{ secrets.FLAKE_AUTOUPDATE_APP_PRIVATE_KEY }}'
      # Opens a PR against the default branch.
      - name: Run `nix flake update`
        run: nix flake update
      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes from `nix flake update`."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Changes detected."
          fi
      - name: Create or update PR
        id: cpr
        if: env.skip != 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          body: "Automatic update via `nix flake update`"
          branch: automatic-flake-update
          commit-message: "flake: automatic update"
          delete-branch: false
          labels: |
            dependencies
          title: "flake: automatic update"
          token: '${{ steps.app-token.outputs.token }}'
      - name: Mark PR as auto-merge
        if: env.skip != 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: 'merge'
          token: '${{ steps.app-token.outputs.token }}'
          pull-request-number: '${{ steps.cpr.outputs.pull-request-number }}'
